name: Build Docker image and push it to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout git branch
        uses: actions/checkout@v2
      -
        name: Prepare the environment variables for tagging the image
        id: prep
        run: |
          DOCKER_IMAGE=${{ github.repository }}
          VERSION=${GITHUB_REF#refs/tags/}
          MINOR=${VERSION%.*}
          MAJOR=${MINOR%.*}
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
      -
        name: Docker image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
