name: Deploy to Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku container registry
        uses: docker/login-action@v1.3.0
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_TOKEN }}

      - name: Deploy to Heroku container registry
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME

