name: Deploy to Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku Container registry
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          docker login --username=_ --password=$HEROKU_API_TOKEN registry.heroku.com
          heroku container:push -a $HEROKU_APP_NAME web
          heroku container:release -a $HEROKU_APP_NAME web
