name: Deploy to Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku container registry
        env:
          INPUT_USERNAME: _
          INPUT_PASSWORD: ${{ secrets.HEROKU_API_TOKEN }}
          INPUT_REGISTRY: registry.heroku.com
        run: docker run docker/github-actions login

      - name: Deploy to Heroku container registry
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME

