name: Test and lint Python files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
    -
      name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --extend-exclude=.venv/,.ipynb_checkpoints/ --count --select=E9,F63,F7,F82 --show-source --statistics
    -
      name: Check static type annotations with mypy
      run: |
        python -m mypy ./ src/ scripts/ scripts/test/ tests/ --ignore-missing-imports
    -
      name: Test with pytest
      run: |
        python -m pytest
